---
- name: (re)start pghttpreq container
  docker_container:
    name: "{{ pghttpreq_docker_name }}"
    image: "{{ pghttpreq_docker_image }}"
    network_mode: host
    env:
      PGHOST: "{{ pghttpreq_host }}"
      PGDATABASE: "{{ pghttpreq_db }}"
      PGUSER: "{{ pghttpreq_user }}"
      PGPASSWORD: "{{ pghttpreq_password }}"
      DB_SCHEMA: "{{ pghttpreq_schema }}"
      PG_CHANNEL: "{{ pghttpreq_channel }}"
      LOGLEVEL: "{{ pghttpreq_loglevel }}"
    restart_policy: always
    restart: "{{ __pghttpreq_restart | default(false) }}"
    pull: true
    state: "started"
