---
- name: Prepare
  hosts: all

  vars:
    postgresql_users:
      - name: postgres
        password: test
      - name: pghttpreq
        password: pghttpreq
        priv: "CREATE"
        db: "postgres"
    postgresql_hba_entries:
      - { type: local, database: all, user: all, auth_method: peer }
      - { type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: trust }

  roles:
    - role: geerlingguy.postgresql
